---
title: "num_providers"
output: html_document
---


<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(data.table) -->
<!-- va_fcc_dec_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/VA-Fixed-Dec2020-v1.csv") -->
<!-- va_fcc_june_2020 <- fread("VA-Fixed-Jun2020-v1.csv") -->
<!-- va_fcc_dec_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/FCC/VA-Fixed-Dec2019-v1.csv") -->
<!-- va_fcc_june_2019 <- fread("VA-Fixed-Jun2019-v2.csv") -->
<!-- va_fcc_dec_2018 <- fread("VA-Fixed-Dec2018-v3.csv") -->
<!-- va_fcc_june_2018 <- fread("VA-Fixed-Jun2018-v1.csv") -->
<!-- va_fcc_dec_2017 <- fread("VA-Fixed-Dec2017-v3.csv") -->
<!-- va_fcc_june_2017 <- fread("VA-Fixed-Jun2017-v3.csv") -->
<!-- va_fcc_dec_2016 <- fread("VA-Fixed-Dec2016-v2.csv") -->
<!-- va_fcc_june_2016 <- fread("VA-Fixed-Jun2016-v4.csv") -->
<!-- va_fcc_dec_2015 <- fread("VA-Fixed-Dec2015-v4.csv") -->
<!-- va_fcc_june_2015 <- fread("VA-Fixed-Jun2015-v5.csv") -->
<!-- va_fcc_dec_2014 <- fread("VA-Fixed-Dec2014-v3.csv") -->

<!-- ### COUNTY -->
<!-- # read ACS county -->
<!-- va.co <- get_acs(geography = "county", -->
<!--                  year = 2019, -->
<!--                  variables = c(tpop = "B01003_001"), -->
<!--                  state = "VA", -->
<!--                  survey = "acs5", -->
<!--                  output = "wide", -->
<!--                  geometry = TRUE) -->

<!-- provider_to_count <- function(va_fcc_dec_2019, year, dec) -->
<!-- { -->
<!--   va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode) -->
<!--   va_fcc_dec_2019$county_code <- substr(va_fcc_dec_2019$BlockCode, 1, 5) -->
<!--   va_fcc_dec_2019$county_code[va_fcc_dec_2019$county_code == "51515"] = "51019" -->
<!--   counts_dec_2019 <- va_fcc_dec_2019 %>% -->
<!--     group_by(county_code) %>% -->
<!--     summarise(num_providers = n_distinct(ProviderName)) %>% -->
<!--     rename(geoid = county_code, -->
<!--            value = num_providers) %>% -->
<!--     mutate(region_type = "county", -->
<!--            measure_type = "count", -->
<!--            measure = ifelse(dec, "num_providers_dec", "num_providers_june"), -->
<!--            measure_units = as.character(NA), -->
<!--            year = year) %>% -->
<!--     merge(st_drop_geometry(va.co[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>% -->
<!--     rename(region_name = NAME) %>% -->
<!--     relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") -->
<!--   return(counts_dec_2019) -->
<!-- } -->

<!-- provider_to_count(va_fcc_june_2020, 2020, F) -> counts_june_2020 -->
<!-- provider_to_count(va_fcc_dec_2019, 2019, T) -> counts_dec_2019 -->
<!-- provider_to_count(va_fcc_june_2019, 2019, F) -> counts_june_2019 -->
<!-- provider_to_count(va_fcc_dec_2018, 2018, T) -> counts_dec_2018 -->
<!-- provider_to_count(va_fcc_june_2018, 2018, F) -> counts_june_2018 -->
<!-- provider_to_count(va_fcc_dec_2017, 2017, T) -> counts_dec_2017 -->
<!-- provider_to_count(va_fcc_june_2017, 2017, F) -> counts_june_2017 -->
<!-- provider_to_count(va_fcc_dec_2016, 2016, T) -> counts_dec_2016 -->
<!-- provider_to_count(va_fcc_june_2016, 2016, F) -> counts_june_2016 -->
<!-- provider_to_count(va_fcc_dec_2015, 2015, T) -> counts_dec_2015 -->
<!-- provider_to_count(va_fcc_june_2015, 2015, F) -> counts_june_2015 -->
<!-- provider_to_count(va_fcc_dec_2014, 2014, T) -> counts_dec_2014 -->

<!-- provider_data <- rbind(counts_june_2020, counts_dec_2019, counts_june_2019, counts_dec_2018, -->
<!--                        counts_june_2018, counts_dec_2017, counts_june_2017, counts_dec_2016, -->
<!--                        counts_june_2016, counts_dec_2015, counts_june_2015, counts_dec_2014) -->
<!-- provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T)) -->
<!-- all_data_COUNTY <- provider_annual_data %>% -->
<!--   rename(value = mean_annual_count) %>% -->
<!--   mutate(measure = "mean_annual_count", -->
<!--          measure_type = "count", -->
<!--          measure_units = as.character(NA), -->
<!--          region_type = "county") %>% -->
<!--   relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>% -->
<!--   rbind(provider_data) -->

<!-- ### TRACT -->
<!-- va.tr <- get_acs(geography = "tract", -->
<!--                  year = 2019, -->
<!--                  variables = c(tpop = "B01003_001"), -->
<!--                  state = "VA", -->
<!--                  survey = "acs5", -->
<!--                  output = "wide", -->
<!--                  geometry = TRUE) -->

<!-- provider_to_count_tracts <- function(va_fcc_dec_2019, year, dec) -->
<!-- { -->
<!--   va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode) -->
<!--   va_fcc_dec_2019$tract_code <- substr(va_fcc_dec_2019$BlockCode, 1, 11) -->
<!--   # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019" -->
<!--   counts_dec_2019 <- va_fcc_dec_2019 %>% -->
<!--     group_by(tract_code) %>% -->
<!--     summarise(num_providers = n_distinct(ProviderName)) %>% -->
<!--     rename(geoid = tract_code, -->
<!--            value = num_providers) %>% -->
<!--     mutate(region_type = "tract", -->
<!--            measure_type = "count", -->
<!--            measure = ifelse(dec, "num_providers_dec", "num_providers_june"), -->
<!--            measure_units = as.character(NA), -->
<!--            year = year) %>% -->
<!--     merge(st_drop_geometry(va.tr[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>% -->
<!--     rename(region_name = NAME) %>% -->
<!--     relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") -->
<!--   return(counts_dec_2019) -->
<!-- } -->

<!-- provider_to_count_tracts(va_fcc_june_2020, 2020, F) -> counts_june_2020 -->
<!-- provider_to_count_tracts(va_fcc_dec_2019, 2019, T) -> counts_dec_2019 -->
<!-- provider_to_count_tracts(va_fcc_june_2019, 2019, F) -> counts_june_2019 -->
<!-- provider_to_count_tracts(va_fcc_dec_2018, 2018, T) -> counts_dec_2018 -->
<!-- provider_to_count_tracts(va_fcc_june_2018, 2018, F) -> counts_june_2018 -->
<!-- provider_to_count_tracts(va_fcc_dec_2017, 2017, T) -> counts_dec_2017 -->
<!-- provider_to_count_tracts(va_fcc_june_2017, 2017, F) -> counts_june_2017 -->
<!-- provider_to_count_tracts(va_fcc_dec_2016, 2016, T) -> counts_dec_2016 -->
<!-- provider_to_count_tracts(va_fcc_june_2016, 2016, F) -> counts_june_2016 -->
<!-- provider_to_count_tracts(va_fcc_dec_2015, 2015, T) -> counts_dec_2015 -->
<!-- provider_to_count_tracts(va_fcc_june_2015, 2015, F) -> counts_june_2015 -->
<!-- provider_to_count_tracts(va_fcc_dec_2014, 2014, T) -> counts_dec_2014 -->

<!-- provider_data <- rbind(counts_june_2020, counts_dec_2019, counts_june_2019, counts_dec_2018, -->
<!--                        counts_june_2018, counts_dec_2017, counts_june_2017, counts_dec_2016, -->
<!--                        counts_june_2016, counts_dec_2015, counts_june_2015, counts_dec_2014) -->
<!-- provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T)) -->
<!-- all_data_tracts <- provider_annual_data %>% -->
<!--   rename(value = mean_annual_count) %>% -->
<!--   mutate(measure = "mean_annual_count", -->
<!--          measure_type = "count", -->
<!--          measure_units = as.character(NA), -->
<!--          region_type = "tract") %>% -->
<!--   relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>% -->
<!--   rbind(provider_data) -->

<!-- ### Health Districts -->
<!-- con <- get_db_conn(db_pass = "rsu8zvrsu8zv") -->
<!-- health_district_geoids <- st_read(con, query = "SELECT * FROM dc_common.va_hd_sdad_2021_virginia_health_district_geoids") -->
<!-- dbDisconnect(con) -->
<!-- health_district <- fread("/project/biocomplexity/sdad/projects_data/vdh/va_county_to_hd.csv") -->
<!-- health_district$county_id <- as.character(health_district$county_id) -->

<!-- va.hd <- merge(health_district, health_district_geoids[, c("region_name", "geoid")], by.x = "health_district", by.y = "region_name") -->

<!-- provider_to_count_hd <- function(va_fcc_dec_2019, year, dec) -->
<!-- { -->
<!--   va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode) -->
<!--   va_fcc_dec_2019$county_code <- substr(va_fcc_dec_2019$BlockCode, 1, 5) -->
<!--   va_fcc_dec_2019$county_code[va_fcc_dec_2019$county_code == "51515"] = "51019" -->
<!--   va_fcc_dec_2019 <- merge(va_fcc_dec_2019, va.hd, by.x = "county_code", by.y = "county_id") -->

<!--   counts_dec_2019 <- va_fcc_dec_2019 %>% -->
<!--     group_by(geoid, health_district) %>% -->
<!--     summarise(num_providers = n_distinct(ProviderName)) %>% -->
<!--     rename(value = num_providers) %>% -->
<!--     mutate(region_type = "health district", -->
<!--            measure_type = "count", -->
<!--            measure = ifelse(dec, "num_providers_dec", "num_providers_june"), -->
<!--            measure_units = as.character(NA), -->
<!--            year = year) %>% -->
<!--     rename(region_name = health_district) %>% -->
<!--     relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") -->
<!--   return(counts_dec_2019) -->
<!-- } -->

<!-- provider_to_count_hd(va_fcc_june_2020, 2020, F) -> counts_june_2020 -->
<!-- provider_to_count_hd(va_fcc_dec_2019, 2019, T) -> counts_dec_2019 -->
<!-- provider_to_count_hd(va_fcc_june_2019, 2019, F) -> counts_june_2019 -->
<!-- provider_to_count_hd(va_fcc_dec_2018, 2018, T) -> counts_dec_2018 -->
<!-- provider_to_count_hd(va_fcc_june_2018, 2018, F) -> counts_june_2018 -->
<!-- provider_to_count_hd(va_fcc_dec_2017, 2017, T) -> counts_dec_2017 -->
<!-- provider_to_count_hd(va_fcc_june_2017, 2017, F) -> counts_june_2017 -->
<!-- provider_to_count_hd(va_fcc_dec_2016, 2016, T) -> counts_dec_2016 -->
<!-- provider_to_count_hd(va_fcc_june_2016, 2016, F) -> counts_june_2016 -->
<!-- provider_to_count_hd(va_fcc_dec_2015, 2015, T) -> counts_dec_2015 -->
<!-- provider_to_count_hd(va_fcc_june_2015, 2015, F) -> counts_june_2015 -->
<!-- provider_to_count_hd(va_fcc_dec_2014, 2014, T) -> counts_dec_2014 -->

<!-- provider_data <- rbind(counts_june_2020, counts_dec_2019, counts_june_2019, counts_dec_2018, -->
<!--                        counts_june_2018, counts_dec_2017, counts_june_2017, counts_dec_2016, -->
<!--                        counts_june_2016, counts_dec_2015, counts_june_2015, counts_dec_2014) -->
<!-- provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T)) -->
<!-- all_data_hd <- provider_annual_data %>% -->
<!--   rename(value = mean_annual_count) %>% -->
<!--   mutate(measure = "mean_annual_count", -->
<!--          measure_type = "count", -->
<!--          measure_units = as.character(NA), -->
<!--          region_type = "health district") %>% -->
<!--   relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>% -->
<!--   rbind(provider_data) -->

<!-- source("~/git/VDH/src/helper_functions.R") -->
<!-- con <- get_db_conn(db_pass = "rsu8zvrsu8zv") -->
<!-- dc_dbWriteTable(con, "dc_digital_communications", "va_tr_fcc_2014_2020_number_of_providers", all_data_tracts) -->
<!-- dc_dbWriteTable(con, "dc_digital_communications", "va_ct_fcc_2014_2020_number_of_providers", all_data_COUNTY) -->
<!-- dc_dbWriteTable(con, "dc_digital_communications", "va_hd_fcc_2014_2020_number_of_providers", all_data_hd) -->
<!-- dbDisconnect(con) -->
<!-- ``` -->



```{r}
library(dplyr)
library(data.table)
va_fcc_jun_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Jun2020-v2.csv")
va_fcc_jun_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Jun2019-v2.csv")
va_fcc_jun_2018 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Jun2018-v1.csv")
va_fcc_jun_2017 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Jun2017-v3.csv")
va_fcc_jun_2016 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Jun2016-v4.csv")
va_fcc_jun_2015 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Jun2015-v5.csv")
va_fcc_dec_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2020-v1.csv")
va_fcc_dec_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2019-v1.csv")
va_fcc_dec_2018 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2018-v3.csv")
va_fcc_dec_2017 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2017-v3.csv")
va_fcc_dec_2016 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2016-v2.csv")
va_fcc_dec_2015 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2015-v4.csv")
va_fcc_dec_2014 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/VA-Fixed-Dec2014-v3.csv")

md_fcc_jun_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Jun2020-v2.csv")
md_fcc_jun_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Jun2019-v2.csv")
md_fcc_jun_2018 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Jun2018-v1.csv")
md_fcc_jun_2017 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Jun2017-v3.csv")
md_fcc_jun_2016 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Jun2016-v4.csv")
md_fcc_jun_2015 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Jun2015-v5.csv")
md_fcc_dec_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2020-v1.csv")
md_fcc_dec_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2019-v1.csv")
md_fcc_dec_2018 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2018-v3.csv")
md_fcc_dec_2017 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2017-v3.csv")
md_fcc_dec_2016 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2016-v2.csv")
md_fcc_dec_2015 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2015-v4.csv")
md_fcc_dec_2014 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/MD-Fixed-Dec2014-v3.csv")

dc_fcc_jun_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Jun2020-v2.csv")
dc_fcc_jun_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Jun2019-v2.csv")
dc_fcc_jun_2018 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Jun2018-v1.csv")
dc_fcc_jun_2017 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Jun2017-v3.csv")
dc_fcc_jun_2016 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Jun2016-v4.csv")
dc_fcc_jun_2015 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Jun2015-v5.csv")
dc_fcc_dec_2020 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2020-v1.csv")
dc_fcc_dec_2019 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2019-v1.csv")
dc_fcc_dec_2018 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2018-v3.csv")
dc_fcc_dec_2017 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2017-v3.csv")
dc_fcc_dec_2016 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2016-v2.csv")
dc_fcc_dec_2015 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2015-v4.csv")
dc_fcc_dec_2014 <- fread("/project/biocomplexity/sdad/projects_data/mc/data_commons/dc_digital_communications/FCC_num_providers/DC-Fixed-Dec2014-v3.csv")
```


```{r}
### COUNTY
# read ACS county
library(sf)
library(tidyverse)
library(tmap)
library(tmaptools)
library(tigris)
library(tidycensus)
library(rmapshaper)
library(matrixStats)
library(SpatialAcc)
library(reticulate)
library(dplyr)
library(tidygeocoder)
library(readxl)

va.co <- get_acs(geography = "county",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "VA",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

va_ct_provider_to_count <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$county_code <- substr(va_fcc_dec_2019$BlockCode, 1, 5)
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(county_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = county_code,
           value = num_providers) %>%
    mutate(region_type = "county",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(va.co[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

va_ct_provider_to_count(va_fcc_jun_2020, 2020, F) -> counts_jun_2020
va_ct_provider_to_count(va_fcc_jun_2019, 2019, F) -> counts_jun_2019
va_ct_provider_to_count(va_fcc_jun_2018, 2018, F) -> counts_jun_2018
va_ct_provider_to_count(va_fcc_jun_2017, 2017, F) -> counts_jun_2017
va_ct_provider_to_count(va_fcc_jun_2016, 2016, F) -> counts_jun_2016
va_ct_provider_to_count(va_fcc_jun_2015, 2015, F) -> counts_jun_2015
va_ct_provider_to_count(va_fcc_dec_2020, 2020, F) -> counts_dec_2020
va_ct_provider_to_count(va_fcc_dec_2019, 2019, F) -> counts_dec_2019
va_ct_provider_to_count(va_fcc_dec_2018, 2018, F) -> counts_dec_2018
va_ct_provider_to_count(va_fcc_dec_2017, 2017, F) -> counts_dec_2017
va_ct_provider_to_count(va_fcc_dec_2016, 2016, F) -> counts_dec_2016
va_ct_provider_to_count(va_fcc_dec_2015, 2015, F) -> counts_dec_2015
va_ct_provider_to_count(va_fcc_dec_2014, 2014, F) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm = T))
va_data_COUNTY <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "county") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### TRACT
va.tr <- get_acs(geography = "tract",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "VA",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

va_provider_to_count_tracts <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$tract_code <- substr(va_fcc_dec_2019$BlockCode, 1, 11)
  # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(tract_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = tract_code,
           value = num_providers) %>%
    mutate(region_type = "tract",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(va.tr[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

va_provider_to_count_tracts(va_fcc_dec_2020, 2020, T) -> counts_dec_2020
va_provider_to_count_tracts(va_fcc_jun_2020, 2020, F) -> counts_jun_2020
va_provider_to_count_tracts(va_fcc_dec_2019, 2019, T) -> counts_dec_2019
va_provider_to_count_tracts(va_fcc_jun_2019, 2019, F) -> counts_jun_2019
va_provider_to_count_tracts(va_fcc_dec_2018, 2018, T) -> counts_dec_2018
va_provider_to_count_tracts(va_fcc_jun_2018, 2018, F) -> counts_jun_2018
va_provider_to_count_tracts(va_fcc_dec_2017, 2017, T) -> counts_dec_2017
va_provider_to_count_tracts(va_fcc_jun_2017, 2017, F) -> counts_jun_2017
va_provider_to_count_tracts(va_fcc_dec_2016, 2016, T) -> counts_dec_2016
va_provider_to_count_tracts(va_fcc_jun_2016, 2016, F) -> counts_jun_2016
va_provider_to_count_tracts(va_fcc_dec_2015, 2015, T) -> counts_dec_2015
va_provider_to_count_tracts(va_fcc_jun_2015, 2015, F) -> counts_jun_2015
va_provider_to_count_tracts(va_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
va_data_tracts <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "tract") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### Health Districts
con <- get_db_conn(db_pass = "rsu8zvrsu8zv")
health_district_geoids <- st_read(con, query = "SELECT * FROM dc_common.va_hd_sdad_2021_virginia_health_district_geoids")
dbDisconnect(con)
health_district <- fread("/project/biocomplexity/sdad/projects_data/vdh/va_county_to_hd.csv")
health_district$county_id <- as.character(health_district$county_id)

va.hd <- merge(health_district, health_district_geoids[, c("region_name", "geoid")], by.x = "health_district", by.y = "region_name")

provider_to_count_hd <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$county_code <- substr(va_fcc_dec_2019$BlockCode, 1, 5)
  va_fcc_dec_2019$county_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  va_fcc_dec_2019 <- merge(va_fcc_dec_2019, va.hd, by.x = "county_code", by.y = "county_id")
  
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(geoid, health_district) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(value = num_providers) %>%
    mutate(region_type = "health district",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    rename(region_name = health_district) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

provider_to_count_hd(va_fcc_dec_2020, 2020, T) -> counts_dec_2020
provider_to_count_hd(va_fcc_jun_2020, 2020, F) -> counts_jun_2020
provider_to_count_hd(va_fcc_dec_2019, 2019, T) -> counts_dec_2019
provider_to_count_hd(va_fcc_jun_2019, 2019, F) -> counts_jun_2019
provider_to_count_hd(va_fcc_dec_2018, 2018, T) -> counts_dec_2018
provider_to_count_hd(va_fcc_jun_2018, 2018, F) -> counts_jun_2018
provider_to_count_hd(va_fcc_dec_2017, 2017, T) -> counts_dec_2017
provider_to_count_hd(va_fcc_jun_2017, 2017, F) -> counts_jun_2017
provider_to_count_hd(va_fcc_dec_2016, 2016, T) -> counts_dec_2016
provider_to_count_hd(va_fcc_jun_2016, 2016, F) -> counts_jun_2016
provider_to_count_hd(va_fcc_dec_2015, 2015, T) -> counts_dec_2015
provider_to_count_hd(va_fcc_jun_2015, 2015, F) -> counts_jun_2015
provider_to_count_hd(va_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
va_data_hd <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "health district") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### BG
va.bg <- get_acs(geography = "block group",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "VA",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

va_provider_to_count_bg <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$bg_code <- substr(va_fcc_dec_2019$BlockCode, 1, 12)
  # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(bg_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = bg_code,
           value = num_providers) %>%
    mutate(region_type = "block group",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(va.bg[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

va_provider_to_count_bg(va_fcc_dec_2020, 2020, T) -> counts_dec_2020
va_provider_to_count_bg(va_fcc_jun_2020, 2020, F) -> counts_jun_2020
va_provider_to_count_bg(va_fcc_dec_2019, 2019, T) -> counts_dec_2019
va_provider_to_count_bg(va_fcc_jun_2019, 2019, F) -> counts_jun_2019
va_provider_to_count_bg(va_fcc_dec_2018, 2018, T) -> counts_dec_2018
va_provider_to_count_bg(va_fcc_jun_2018, 2018, F) -> counts_jun_2018
va_provider_to_count_bg(va_fcc_dec_2017, 2017, T) -> counts_dec_2017
va_provider_to_count_bg(va_fcc_jun_2017, 2017, F) -> counts_jun_2017
va_provider_to_count_bg(va_fcc_dec_2016, 2016, T) -> counts_dec_2016
va_provider_to_count_bg(va_fcc_jun_2016, 2016, F) -> counts_jun_2016
va_provider_to_count_bg(va_fcc_dec_2015, 2015, T) -> counts_dec_2015
va_provider_to_count_bg(va_fcc_jun_2015, 2015, F) -> counts_jun_2015
va_provider_to_count_bg(va_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
va_data_bg <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "block group") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

# source("~/git/VDH/src/helper_functions.R")
# con <- get_db_conn(db_pass = "rsu8zvrsu8zv")
# dc_dbWriteTable(con, "dc_digital_communications", "va_tr_fcc_2014_2020_number_of_providers", all_data_tracts)
# dc_dbWriteTable(con, "dc_digital_communications", "va_ct_fcc_2014_2020_number_of_providers", all_data_COUNTY)
# dc_dbWriteTable(con, "dc_digital_communications", "va_hd_fcc_2014_2020_number_of_providers", all_data_hd)
# dbDisconnect(con)

va_provider_data <- rbind(va_data_bg, va_data_tracts, va_data_COUNTY)
va_provider_data
```


```{r}
### COUNTY
md.co <- get_acs(geography = "county",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "MD",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

md_ct_provider_to_count <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$county_code <- substr(va_fcc_dec_2019$BlockCode, 1, 5)
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(county_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = county_code,
           value = num_providers) %>%
    mutate(region_type = "county",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(md.co[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

md_ct_provider_to_count(md_fcc_jun_2020, 2020, F) -> counts_jun_2020
md_ct_provider_to_count(md_fcc_jun_2019, 2019, F) -> counts_jun_2019
md_ct_provider_to_count(md_fcc_jun_2018, 2018, F) -> counts_jun_2018
md_ct_provider_to_count(md_fcc_jun_2017, 2017, F) -> counts_jun_2017
md_ct_provider_to_count(md_fcc_jun_2016, 2016, F) -> counts_jun_2016
md_ct_provider_to_count(md_fcc_jun_2015, 2015, F) -> counts_jun_2015
md_ct_provider_to_count(md_fcc_dec_2020, 2020, T) -> counts_dec_2020
md_ct_provider_to_count(md_fcc_dec_2019, 2019, T) -> counts_dec_2019
md_ct_provider_to_count(md_fcc_dec_2018, 2018, T) -> counts_dec_2018
md_ct_provider_to_count(md_fcc_dec_2017, 2017, T) -> counts_dec_2017
md_ct_provider_to_count(md_fcc_dec_2016, 2016, T) -> counts_dec_2016
md_ct_provider_to_count(md_fcc_dec_2015, 2015, T) -> counts_dec_2015
md_ct_provider_to_count(md_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm = T))
md_data_COUNTY <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "county") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### TRACT
md.tr <- get_acs(geography = "tract",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "MD",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

md_provider_to_count_tracts <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$tract_code <- substr(va_fcc_dec_2019$BlockCode, 1, 11)
  # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(tract_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = tract_code,
           value = num_providers) %>%
    mutate(region_type = "tract",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(md.tr[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

md_provider_to_count_tracts(md_fcc_dec_2020, 2020, T) -> counts_dec_2020
md_provider_to_count_tracts(md_fcc_jun_2020, 2020, F) -> counts_jun_2020
md_provider_to_count_tracts(md_fcc_dec_2019, 2019, T) -> counts_dec_2019
md_provider_to_count_tracts(md_fcc_jun_2019, 2019, F) -> counts_jun_2019
md_provider_to_count_tracts(md_fcc_dec_2018, 2018, T) -> counts_dec_2018
md_provider_to_count_tracts(md_fcc_jun_2018, 2018, F) -> counts_jun_2018
md_provider_to_count_tracts(md_fcc_dec_2017, 2017, T) -> counts_dec_2017
md_provider_to_count_tracts(md_fcc_jun_2017, 2017, F) -> counts_jun_2017
md_provider_to_count_tracts(md_fcc_dec_2016, 2016, T) -> counts_dec_2016
md_provider_to_count_tracts(md_fcc_jun_2016, 2016, F) -> counts_jun_2016
md_provider_to_count_tracts(md_fcc_dec_2015, 2015, T) -> counts_dec_2015
md_provider_to_count_tracts(md_fcc_jun_2015, 2015, F) -> counts_jun_2015
md_provider_to_count_tracts(md_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
md_data_tracts <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "tract") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### BG
md.bg <- get_acs(geography = "block group",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "MD",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

md_provider_to_count_bg <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$bg_code <- substr(va_fcc_dec_2019$BlockCode, 1, 12)
  # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(bg_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = bg_code,
           value = num_providers) %>%
    mutate(region_type = "block group",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(md.bg[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

md_provider_to_count_bg(md_fcc_dec_2020, 2020, T) -> counts_dec_2020
md_provider_to_count_bg(md_fcc_jun_2020, 2020, F) -> counts_jun_2020
md_provider_to_count_bg(md_fcc_dec_2019, 2019, T) -> counts_dec_2019
md_provider_to_count_bg(md_fcc_jun_2019, 2019, F) -> counts_jun_2019
md_provider_to_count_bg(md_fcc_dec_2018, 2018, T) -> counts_dec_2018
md_provider_to_count_bg(md_fcc_jun_2018, 2018, F) -> counts_jun_2018
md_provider_to_count_bg(md_fcc_dec_2017, 2017, T) -> counts_dec_2017
md_provider_to_count_bg(md_fcc_jun_2017, 2017, F) -> counts_jun_2017
md_provider_to_count_bg(md_fcc_dec_2016, 2016, T) -> counts_dec_2016
md_provider_to_count_bg(md_fcc_jun_2016, 2016, F) -> counts_jun_2016
md_provider_to_count_bg(md_fcc_dec_2015, 2015, T) -> counts_dec_2015
md_provider_to_count_bg(md_fcc_jun_2015, 2015, F) -> counts_jun_2015
md_provider_to_count_bg(md_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
md_data_bg <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "block group") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

# source("~/git/VDH/src/helper_functions.R")
# con <- get_db_conn(db_pass = "rsu8zvrsu8zv")
# dc_dbWriteTable(con, "dc_digital_communications", "va_tr_fcc_2014_2020_number_of_providers", all_data_tracts)
# dc_dbWriteTable(con, "dc_digital_communications", "va_ct_fcc_2014_2020_number_of_providers", all_data_COUNTY)
# dc_dbWriteTable(con, "dc_digital_communications", "va_hd_fcc_2014_2020_number_of_providers", all_data_hd)
# dbDisconnect(con)

md_provider_data <- rbind(md_data_bg, md_data_tracts, md_data_COUNTY)
md_provider_data
```


```{r}
### COUNTY
dc.co <- get_acs(geography = "county",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "DC",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

dc_ct_provider_to_count <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$county_code <- substr(va_fcc_dec_2019$BlockCode, 1, 5)
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(county_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = county_code,
           value = num_providers) %>%
    mutate(region_type = "county",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(dc.co[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

dc_ct_provider_to_count(dc_fcc_jun_2020, 2020, F) -> counts_jun_2020
dc_ct_provider_to_count(dc_fcc_jun_2019, 2019, F) -> counts_jun_2019
dc_ct_provider_to_count(dc_fcc_jun_2018, 2018, F) -> counts_jun_2018
dc_ct_provider_to_count(dc_fcc_jun_2017, 2017, F) -> counts_jun_2017
dc_ct_provider_to_count(dc_fcc_jun_2016, 2016, F) -> counts_jun_2016
dc_ct_provider_to_count(dc_fcc_jun_2015, 2015, F) -> counts_jun_2015
dc_ct_provider_to_count(dc_fcc_dec_2020, 2020, T) -> counts_dec_2020
dc_ct_provider_to_count(dc_fcc_dec_2019, 2019, T) -> counts_dec_2019
dc_ct_provider_to_count(dc_fcc_dec_2018, 2018, T) -> counts_dec_2018
dc_ct_provider_to_count(dc_fcc_dec_2017, 2017, T) -> counts_dec_2017
dc_ct_provider_to_count(dc_fcc_dec_2016, 2016, T) -> counts_dec_2016
dc_ct_provider_to_count(dc_fcc_dec_2015, 2015, T) -> counts_dec_2015
dc_ct_provider_to_count(dc_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm = T))
dc_data_COUNTY <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "county") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### TRACT
dc.tr <- get_acs(geography = "tract",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "DC",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

dc_provider_to_count_tracts <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$tract_code <- substr(va_fcc_dec_2019$BlockCode, 1, 11)
  # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(tract_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = tract_code,
           value = num_providers) %>%
    mutate(region_type = "tract",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(dc.tr[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

dc_provider_to_count_tracts(dc_fcc_dec_2020, 2020, T) -> counts_dec_2020
dc_provider_to_count_tracts(dc_fcc_jun_2020, 2020, F) -> counts_jun_2020
dc_provider_to_count_tracts(dc_fcc_dec_2019, 2019, T) -> counts_dec_2019
dc_provider_to_count_tracts(dc_fcc_jun_2019, 2019, F) -> counts_jun_2019
dc_provider_to_count_tracts(dc_fcc_dec_2018, 2018, T) -> counts_dec_2018
dc_provider_to_count_tracts(dc_fcc_jun_2018, 2018, F) -> counts_jun_2018
dc_provider_to_count_tracts(dc_fcc_dec_2017, 2017, T) -> counts_dec_2017
dc_provider_to_count_tracts(dc_fcc_jun_2017, 2017, F) -> counts_jun_2017
dc_provider_to_count_tracts(dc_fcc_dec_2016, 2016, T) -> counts_dec_2016
dc_provider_to_count_tracts(dc_fcc_jun_2016, 2016, F) -> counts_jun_2016
dc_provider_to_count_tracts(dc_fcc_dec_2015, 2015, T) -> counts_dec_2015
dc_provider_to_count_tracts(dc_fcc_jun_2015, 2015, F) -> counts_jun_2015
dc_provider_to_count_tracts(dc_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
dc_data_tracts <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "tract") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

### BG
dc.bg <- get_acs(geography = "block group",
                 year = 2019,
                 variables = c(tpop = "B01003_001"),
                 state = "DC",
                 survey = "acs5",
                 output = "wide",
                 geometry = TRUE)

dc_provider_to_count_bg <- function(va_fcc_dec_2019, year, dec)
{
  va_fcc_dec_2019$BlockCode <- as.character(va_fcc_dec_2019$BlockCode)
  va_fcc_dec_2019$bg_code <- substr(va_fcc_dec_2019$BlockCode, 1, 12)
  # va_fcc_dec_2019$tract_code[va_fcc_dec_2019$county_code == "51515"] = "51019"
  counts_dec_2019 <- va_fcc_dec_2019 %>%
    group_by(bg_code) %>%
    summarise(num_providers = n_distinct(ProviderName)) %>%
    rename(geoid = bg_code,
           value = num_providers) %>%
    mutate(region_type = "block group",
           measure_type = "count",
           measure = ifelse(dec, "num_providers_dec", "num_providers_june"),
           measure_units = as.character(NA),
           year = year) %>%
    merge(st_drop_geometry(dc.bg[, c("GEOID", "NAME")]), by.x = "geoid", by.y = "GEOID") %>%
    rename(region_name = NAME) %>%
    relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units")
  return(counts_dec_2019)
}

dc_provider_to_count_bg(dc_fcc_dec_2020, 2020, T) -> counts_dec_2020
dc_provider_to_count_bg(dc_fcc_jun_2020, 2020, F) -> counts_jun_2020
dc_provider_to_count_bg(dc_fcc_dec_2019, 2019, T) -> counts_dec_2019
dc_provider_to_count_bg(dc_fcc_jun_2019, 2019, F) -> counts_jun_2019
dc_provider_to_count_bg(dc_fcc_dec_2018, 2018, T) -> counts_dec_2018
dc_provider_to_count_bg(dc_fcc_jun_2018, 2018, F) -> counts_jun_2018
dc_provider_to_count_bg(dc_fcc_dec_2017, 2017, T) -> counts_dec_2017
dc_provider_to_count_bg(dc_fcc_jun_2017, 2017, F) -> counts_jun_2017
dc_provider_to_count_bg(dc_fcc_dec_2016, 2016, T) -> counts_dec_2016
dc_provider_to_count_bg(dc_fcc_jun_2016, 2016, F) -> counts_jun_2016
dc_provider_to_count_bg(dc_fcc_dec_2015, 2015, T) -> counts_dec_2015
dc_provider_to_count_bg(dc_fcc_jun_2015, 2015, F) -> counts_jun_2015
dc_provider_to_count_bg(dc_fcc_dec_2014, 2014, T) -> counts_dec_2014

provider_data <- rbind(counts_dec_2020, counts_jun_2020, counts_dec_2019, counts_jun_2019, counts_dec_2018,
                       counts_jun_2018, counts_dec_2017, counts_jun_2017, counts_dec_2016, counts_jun_2016,
                       counts_dec_2015, counts_jun_2015, counts_dec_2014)
provider_annual_data <- provider_data %>% group_by(geoid, region_name, year) %>% summarise(mean_annual_count = mean(value, na.rm=T))
dc_data_bg <- provider_annual_data %>%
  rename(value = mean_annual_count) %>%
  mutate(measure = "mean_annual_count",
         measure_type = "count",
         measure_units = as.character(NA),
         region_type = "block group") %>%
  relocate("geoid", "region_type", "region_name", "year", "measure", "value", "measure_type", "measure_units") %>%
  rbind(provider_data)

# source("~/git/VDH/src/helper_functions.R")
# con <- get_db_conn(db_pass = "rsu8zvrsu8zv")
# dc_dbWriteTable(con, "dc_digital_communications", "va_tr_fcc_2014_2020_number_of_providers", all_data_tracts)
# dc_dbWriteTable(con, "dc_digital_communications", "va_ct_fcc_2014_2020_number_of_providers", all_data_COUNTY)
# dc_dbWriteTable(con, "dc_digital_communications", "va_hd_fcc_2014_2020_number_of_providers", all_data_hd)
# dbDisconnect(con)

dc_provider_data <- rbind(dc_data_bg, dc_data_tracts, dc_data_COUNTY)
dc_provider_data
```


```{r}
# combined hd, ct, tr, and bg data
# how do we want to define providers within a county, tract, etc
# (do we add up all of the providers within the blocks within that county??? or is it an average)
va_provider_data$measure <- "annual_mean_num_unique_providers"
md_provider_data$measure <- "annual_mean_num_unique_providers"
dc_provider_data$measure <- "annual_mean_num_unique_providers"

ncr_provider_data <- rbind(va_provider_data, md_provider_data, dc_provider_data)
ncr_provider_data.2 <- ncr_provider_data %>% filter(region_type != "health district") %>% mutate(county = substr(geoid, 1, 5))
ncr_provider_data.3 <- ncr_provider_data.2 %>% filter(county %in% c("51013", "51059", "51107", "51510", "51600", "51153", "51683", "51685", "51610", "11001", "24031", "24033", "24017", "24021")) %>% select(-county)
ncr_provider_data.3$measure <- "annual_mean_num_unique_providers"
  
# A - number of distinct providers in each county
# B - average number of district providers in blocks within geography

con <- get_db_conn(db_pass = "rsu8zvrsu8zv")
dc_dbWriteTable(con, "dc_digital_communications", "va_bgtrcthd_fcc_2014_2020_number_of_providers", va_provider_data)
dc_dbWriteTable(con, "dc_digital_communications", "md_bgtrct_fcc_2014_2020_number_of_providers", md_provider_data)
dc_dbWriteTable(con, "dc_digital_communications", "dc_bgtrct_fcc_2014_2020_number_of_providers", dc_provider_data)
dc_dbWriteTable(con, "dc_digital_communications", "ncr_bgtrct_fcc_2014_2020_number_of_providers", ncr_provider_data.3)
dbDisconnect(con)
```


```{r}
## Install the required package with:
## install.packages("RSocrata")

# library("RSocrata")
# 
# df <- read.socrata(
#   "https://opendata.fcc.gov/resource/hicn-aujz.json?stateabbr=MN",
#   app_token = "brTJGRbG1mCwjR6RKRO3sgrKI",
#   email     = "rsu8zv@virginia.edu",
#   password  = "JPZK2017blah!"
# )
```

